// export const ActionTypes = {
//     FETCH_PRODUCTS:"FETCH_PRODUCTS",
//     SET_PRODUCTS: "SET_PRODUCTS",
//     SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
//     REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
//   };
  

export const FETCH_SELECT = "FETCH_SELECT";
export const FETCH_SELECT_SUCCESS = "FETCH_SELECT_SUCCESS";
export const FETCH_SELECT_FAILURE = "FETCH_SELECT_FAILURE";